targets:
  dynamic_config_generator:dynamic_config_generator:
    builders:
      dynamic_config_generator|config_builder:
        enabled: true

builders:
  config_builder:
    import: "package:dynamic_config_generator/dynamic_config_generator.dart"
    builder_factories: ["configBuilder"]
    build_extensions: {".json": ["build_config.g.part"]}
    build_to: source
    auto_apply: dependents